#!/usr/bin/env bash
# QUICK START - Sistema de Inventarios con Movimientos

# Este script ayuda a iniciar rápidamente

echo "╔════════════════════════════════════════════════════════╗"
echo "║   InventarioPRO v2.1 - Sistema de Inventarios         ║"
echo "║   Con Control de Movimientos y Early Return Pattern    ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Verificar si estamos en la carpeta correcta
if [ ! -f "index.html" ]; then
    echo "❌ Error: Debes ejecutar este script desde la carpeta 'SistemaInventarios'"
    exit 1
fi

echo "📁 Archivos disponibles:"
echo "  ✅ js/productManager.js      (620 líneas - Gestión de productos)"
echo "  ✅ js/movementManager.js     (700 líneas - Movimientos NEW⭐)"
echo "  ✅ js/auth.js                (438 líneas - Autenticación)"
echo "  ✅ index.html                (708 líneas - Interfaz)"
echo ""

echo "📚 Documentación:"
echo "  📖 CRUD_PRODUCTOS.md         - Guía de ProductManager"
echo "  📖 MOVIMIENTOS.md            - Guía de MovementManager"
echo "  📖 SISTEMA_COMPLETO.md       - Arquitectura e integración"
echo "  📖 IMPLEMENTACION_MOVIMIENTOS.md - Detalles técnicos"
echo ""

echo "🧪 Demos interactivos:"
echo "  🎮 demo-crud.html            - CRUD de productos"
echo "  🎮 demo-movements.html       - Movimientos de inventario"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""

# Detectar sistema operativo
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    echo "🪟 Sistema: Windows"
    echo ""
    echo "Para servir los archivos:"
    echo ""
    echo "Opción 1: Con Python"
    echo "  python -m http.server 8000"
    echo ""
    echo "Opción 2: Con Node.js"
    echo "  npx http-server -p 8000"
    echo ""
    echo "Opción 3: Con PowerShell (si Python no está disponible)"
    echo "  python -m http.server 8000"
    echo ""
elif [[ "$OSTYPE" == "linux-gnu"* ]] || [[ "$OSTYPE" == "darwin"* ]]; then
    echo "🐧 Sistema: Unix/Linux/Mac"
    echo ""
    echo "Para servir los archivos:"
    echo ""
    echo "  # Opción 1: Con Python"
    echo "  python3 -m http.server 8000"
    echo ""
    echo "  # Opción 2: Con Node.js"
    echo "  npx http-server -p 8000"
    echo ""
    echo "  # Opción 3: Con php"
    echo "  php -S localhost:8000"
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Después de ejecutar el servidor:"
echo "  🌐 Abre en navegador: http://localhost:8000"
echo "  📱 Para ver demos: http://localhost:8000/demo-*.html"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🚀 PRIMEROS PASOS:"
echo ""
echo "1. Abre el navegador en http://localhost:8000/index.html"
echo "2. Haz login con: usuario/admin123 (admin) o empleado/emp123"
echo "3. Crea un producto (ej: Laptop)"
echo "4. Registra un movimiento (compra, venta, etc)"
echo "5. Verifica el historial y estadísticas"
echo ""
echo "🧪 PARA TESTEAR MOVIMIENTOS:"
echo ""
echo "1. Abre: http://localhost:8000/demo-movements.html"
echo "2. Haz clic en 'Iniciar' para crear un producto de demo"
echo "3. Prueba los botones:"
echo "   - Compra Proveedor → Entrada de stock"
echo "   - Venta Cliente → Salida de stock"
echo "   - Venta Sin Stock → Prueba Early Return (error esperado)"
echo "   - Ver Estadísticas → Análisis de movimientos"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTACIÓN RÁPIDA:"
echo ""
echo "Crear producto:"
echo "  productManager.crearProducto({nombre, codigo, categoriaId, ...})"
echo ""
echo "Registrar entrada:"
echo "  movementManager.registrarEntrada({productoId, cantidad, razon, usuario})"
echo ""
echo "Registrar salida (con Early Return):"
echo "  movementManager.registrarSalida({productoId, cantidad, razon, usuario})"
echo "  // Valida automáticamente: ¿hay stock disponible?"
echo ""
echo "Ver historial:"
echo "  movementManager.obtenerHistorialStock(productoId)"
echo ""
echo "Ver estadísticas:"
echo "  movementManager.obtenerEstadisticas()"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ Sistema listo para usar"
echo ""
